package com.codereview.ai.domain.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * LearningPath Entity - AI-Generated Learning Paths
 *
 * Represents personalized learning paths generated by AI agents for users.
 * Contains structured steps for learning specific programming skills.
 *
 * @author Code Intelligence Service Team
 */
@Entity
@Table(name = "learning_paths", indexes = {
    @Index(name = "idx_learning_paths_user_id", columnList = "user_id"),
    @Index(name = "idx_learning_paths_target_skill", columnList = "target_skill"),
    @Index(name = "idx_learning_paths_status", columnList = "status")
})
@EntityListeners(AuditingEntityListener.class)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LearningPath {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Column(name = "task_id")
    private Long taskId;

    @Column(name = "title", nullable = false, length = 200)
    private String title;

    @Column(name = "target_skill", nullable = false, length = 100)
    private String targetSkill;

    @Column(name = "weeks", nullable = false)
    private Integer weeks;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "steps", columnDefinition = "jsonb")
    private List<Map<String, Object>> steps;

    @Column(name = "status", nullable = false, length = 20)
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private Status status = Status.ACTIVE;

    @Column(name = "progress")
    @Builder.Default
    private Integer progress = 0;

    @Column(name = "current_step")
    private Integer currentStep;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "completed_at")
    private LocalDateTime completedAt;

    /**
     * Status enum defining the possible states of a learning path
     */
    public enum Status {
        ACTIVE,      // Learning path is currently in progress
        COMPLETED,   // Learning path has been completed
        PAUSED,      // Learning path is paused
        ARCHIVED     // Learning path is archived
    }
}
