package com.codereview.ai.domain.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Teaching Report Entity
 *
 * Generated by TeachingMentor based on code review results.
 * Contains educational content, improvement suggestions, and learning resources.
 *
 * @author Code Review AI Team
 */
@Entity
@Table(name = "teaching_reports")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class TeachingReport {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "review_id", insertable = false, updatable = false)
    @JsonIgnore
    private CodeReview review;

    @Column(name = "review_id", nullable = false)
    private Long reviewId;

    @Column(length = 50)
    private String language;

    @Column(columnDefinition = "TEXT")
    private String codeSummary;

    @Column(columnDefinition = "TEXT")
    private String summary;

    @Column(columnDefinition = "TEXT")
    private String knowledgeGapsJson;  // JSON array

    @Column(columnDefinition = "TEXT")
    private String keyFindingsJson;     // JSON array

    @Column(columnDefinition = "TEXT")
    private String learningResourcesJson; // JSON object

    @Column(columnDefinition = "TEXT")
    private String priorityActionsJson;  // JSON array

    @Column(columnDefinition = "TEXT")
    private String encouragement;

    @Column
    private Integer totalIssues;

    @Column
    @Builder.Default
    private Integer criticalIssues = 0;

    @Column
    @Builder.Default
    private Integer highIssues = 0;

    @Column
    @Builder.Default
    private Integer mediumIssues = 0;

    @Column
    @Builder.Default
    private Integer lowIssues = 0;

    @CreatedDate
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    private static final ObjectMapper objectMapper = new ObjectMapper();

    /**
     * Key Finding inner class
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class KeyFinding {
        private String category;
        private String issue;
        private String explanation;
        private String improvement;
        private String severity;
    }

    // ============ Helper methods for JSON fields ============

    /**
     * Get knowledge gaps as list
     */
    public List<String> getKnowledgeGaps() {
        if (knowledgeGapsJson == null || knowledgeGapsJson.isEmpty()) {
            return new ArrayList<>();
        }
        try {
            return objectMapper.readValue(knowledgeGapsJson, new TypeReference<List<String>>() {});
        } catch (JsonProcessingException e) {
            return new ArrayList<>();
        }
    }

    /**
     * Set knowledge gaps from list
     */
    public void setKnowledgeGaps(List<String> gaps) {
        if (gaps == null) {
            this.knowledgeGapsJson = null;
            return;
        }
        try {
            this.knowledgeGapsJson = objectMapper.writeValueAsString(gaps);
        } catch (JsonProcessingException e) {
            this.knowledgeGapsJson = "[]";
        }
    }

    /**
     * Get key findings as list
     */
    public List<KeyFinding> getKeyFindings() {
        if (keyFindingsJson == null || keyFindingsJson.isEmpty()) {
            return new ArrayList<>();
        }
        try {
            return objectMapper.readValue(keyFindingsJson, new TypeReference<List<KeyFinding>>() {});
        } catch (JsonProcessingException e) {
            return new ArrayList<>();
        }
    }

    /**
     * Set key findings from list
     */
    public void setKeyFindings(List<KeyFinding> findings) {
        if (findings == null) {
            this.keyFindingsJson = null;
            return;
        }
        try {
            this.keyFindingsJson = objectMapper.writeValueAsString(findings);
        } catch (JsonProcessingException e) {
            this.keyFindingsJson = "[]";
        }
    }

    /**
     * Get learning resources as map
     */
    public Map<String, List<String>> getLearningResources() {
        if (learningResourcesJson == null || learningResourcesJson.isEmpty()) {
            return new HashMap<>();
        }
        try {
            return objectMapper.readValue(learningResourcesJson, new TypeReference<Map<String, List<String>>>() {});
        } catch (JsonProcessingException e) {
            return new HashMap<>();
        }
    }

    /**
     * Set learning resources from map
     */
    public void setLearningResources(Map<String, List<String>> resources) {
        if (resources == null) {
            this.learningResourcesJson = null;
            return;
        }
        try {
            this.learningResourcesJson = objectMapper.writeValueAsString(resources);
        } catch (JsonProcessingException e) {
            this.learningResourcesJson = "{}";
        }
    }

    /**
     * Get priority actions as list
     */
    public List<String> getPriorityActions() {
        if (priorityActionsJson == null || priorityActionsJson.isEmpty()) {
            return new ArrayList<>();
        }
        try {
            return objectMapper.readValue(priorityActionsJson, new TypeReference<List<String>>() {});
        } catch (JsonProcessingException e) {
            return new ArrayList<>();
        }
    }

    /**
     * Set priority actions from list
     */
    public void setPriorityActions(List<String> actions) {
        if (actions == null) {
            this.priorityActionsJson = null;
            return;
        }
        try {
            this.priorityActionsJson = objectMapper.writeValueAsString(actions);
        } catch (JsonProcessingException e) {
            this.priorityActionsJson = "[]";
        }
    }
}
