-- ================================================================
-- Add metadata column to code_issues table
-- ================================================================
ALTER TABLE code_issues
ADD COLUMN IF NOT EXISTS metadata TEXT;

COMMENT ON COLUMN code_issues.metadata IS 'JSON metadata for additional information (e.g., method count, complexity scores, etc.)';

-- ================================================================
-- Create teaching_reports table for storing AI-generated teaching content
-- ================================================================
CREATE TABLE IF NOT EXISTS teaching_reports (
    id BIGSERIAL PRIMARY KEY,
    review_id BIGINT NOT NULL,
    language VARCHAR(50),
    code_summary TEXT,
    summary TEXT,
    knowledge_gaps_json TEXT,
    key_findings_json TEXT,
    learning_resources_json TEXT,
    priority_actions_json TEXT,
    encouragement TEXT,
    total_issues INT DEFAULT 0,
    critical_issues INT DEFAULT 0,
    high_issues INT DEFAULT 0,
    medium_issues INT DEFAULT 0,
    low_issues INT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_teaching_report_review FOREIGN KEY (review_id)
        REFERENCES code_reviews(id) ON DELETE CASCADE
);

-- Create indexes for teaching_reports
CREATE INDEX IF NOT EXISTS idx_teaching_reports_review_id ON teaching_reports(review_id);
CREATE INDEX IF NOT EXISTS idx_teaching_reports_language ON teaching_reports(language);
CREATE INDEX IF NOT EXISTS idx_teaching_reports_created_at ON teaching_reports(created_at DESC);

-- Add table and column comments
COMMENT ON TABLE teaching_reports IS 'Teaching reports generated by AI mentor based on code review results';
COMMENT ON COLUMN teaching_reports.knowledge_gaps_json IS 'JSON array of knowledge gaps identified';
COMMENT ON COLUMN teaching_reports.key_findings_json IS 'JSON array of key findings with explanations';
COMMENT ON COLUMN teaching_reports.learning_resources_json IS 'JSON object mapping topics to learning resources';
COMMENT ON COLUMN teaching_reports.priority_actions_json IS 'JSON array of priority actions for improvement';
